%{
This model is generated by:
- Loading terrain map
- Creating threats as cylinders
- Creating start and finish points
- Setting ranges and limits
%}

function model=CreateModel()

H = imread('ChrismasTerrain.tif'); % Get elevation data
H (H < 0) = 0;
MAPSIZE_X = size(H,2); % x index: columns of H
MAPSIZE_Y = size(H,1); % y index: rows of H
[X,Y] = meshgrid(1:MAPSIZE_X,1:MAPSIZE_Y); % Create all (x,y) points to plot

R1=130;  % Radius
x1 = 170; y1 = 330; z1 = 150; Hc1 = 350; % center

R2=130;  % Radius
x2 = 430; y2 = 150; z2 = 150;Hc2 = 350; % center

R3=50;  % Radius
x3 = 300; y3 = 240; z3 = 150;Hc3 = 200; % center

R4=70;  % Radius
x4 = 750; y4 = 640; z4 = 150;Hc4 = 180; % center

R5=70;  % Radius
x5 = 500; y5 = 450; z5 = 150;Hc5 = 350;% center

R6=100;  % Radius
x6 = 620; y6 = 730; z6 = 150;Hc6 = 350;% center

R7=100;  % Radius
x7 = 880; y7 = 550; z7 = 150;Hc7 = 350; % center

  
    % Map limits
    xmin= 1;
    xmax= MAPSIZE_X;
    
    ymin= 1;
    ymax= MAPSIZE_Y;
    
    zmin = 100;
    zmax = 200;  

 
    % Start and end position
    start_location = [220;80;150];
    end_location = [850;750;150];
    
    % Number of path nodes (not including the start position (start node))
    n=10;
    
    % Incorporate map and searching parameters to a model
    model.start=start_location;
    model.end=end_location;
    model.n=n;
    model.xmin=xmin;
    model.xmax=xmax;
    model.zmin=zmin;
    model.ymin=ymin;
    model.ymax=ymax;
    model.zmax=zmax;
    model.MAPSIZE_X = MAPSIZE_X;
    model.MAPSIZE_Y = MAPSIZE_Y;
    model.X = X;
    model.Y = Y;
    model.H = H;
    %model.threats = [x1 y1 z1 R1 Hc1;x2 y2 z2 R2 Hc2; x3 y3 z3 R3 Hc3; x4 y4 z4 R4 Hc4; x5 y5 z5 R5 Hc5;x6 y6 z6 R6 Hc6;x7 y7 z7 R7 Hc7;x8 y8 z8 R8 Hc8];
    model.threats = [x1 y1 z1 R1 Hc1;x2 y2 z2 R2 Hc2; x3 y3 z3 R3 Hc3; x4 y4 z4 R4 Hc4; x5 y5 z5 R5 Hc5;x6 y6 z6 R6 Hc6;x7 y7 z7 R7 Hc7];
    PlotModel(model);
    minHeight = min(H(:));
maxHeight = max(H(:));
disp(['Actual Minimum Height: ' num2str(minHeight)]);
disp(['Actual Maximum Height: ' num2str(maxHeight)]);

end
